//! ffmpeg-backed integration tests for the decode/probe/pcm/thumbnail/waveform
//! and encode round-trip paths.
//!
//! These verify the chosen `ffmpeg-sidecar` (CLI) backend works end-to-end with
//! the locally installed ffmpeg (8.1 here). They **auto-skip** when ffmpeg /
//! ffprobe are not on `PATH`, so the default `cargo test` stays green and offline
//! on machines without ffmpeg — the test fixtures are generated by ffmpeg itself
//! (lavfi sources), so nothing is downloaded.

use std::path::Path;
use std::process::Command;

use opentake_media::decode::frame::FrameDecodeStream;
use opentake_media::decode::spawn_video_stream;
use opentake_media::ffmpeg_status::{ffmpeg_available, ffprobe_available};
use opentake_media::{
    decode_frame_at, encode, extract_pcm, probe, video_thumbnails, waveform, ExportPreset,
    ExportResolution, FrameRequest, PcmFormat, PcmSpec, RgbaFrame, VideoCodec, VideoEncoder,
    VideoStreamRequest,
};

/// Generate a 2 s 320x240@10fps test video with a 440 Hz sine audio track.
fn make_av(path: &Path) -> bool {
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=2:size=320x240:rate=10",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=2",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Generate a 1 s silent-but-present sine audio-only file.
fn make_audio(path: &Path) -> bool {
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=220:duration=1",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[test]
fn probe_reports_dimensions_fps_and_audio() {
    if !ffprobe_available() {
        eprintln!("skip: ffprobe not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        eprintln!("skip: could not generate test media");
        return;
    }

    let p = probe(&av).unwrap();
    assert!(p.has_video);
    assert!(p.has_audio);
    assert_eq!(p.width, Some(320));
    assert_eq!(p.height, Some(240));
    assert!(p.fps.unwrap() > 9.0 && p.fps.unwrap() < 11.0);
    assert!(p.duration_secs > 1.5 && p.duration_secs < 2.5);
}

#[test]
fn decode_frame_returns_rgba_of_expected_size() {
    if !ffmpeg_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }

    let req = FrameRequest {
        time_secs: 1.0,
        max_size: (0, 0),
        tolerance_secs: 1.0,
        apply_rotation: true,
    };
    let (_actual, frame) = decode_frame_at(&av, &req).unwrap();
    assert_eq!(frame.width, 320);
    assert_eq!(frame.height, 240);
    assert_eq!(frame.rgba.len(), 320 * 240 * 4);
}

#[test]
fn frame_decode_stream_yields_consecutive_scaled_frames() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let request = FrameRequest {
        time_secs: 0.5,
        max_size: (120, 68),
        tolerance_secs: 0.0,
        apply_rotation: true,
    };
    let expected = decode_frame_at(&av, &request).unwrap().1;
    let mut stream = FrameDecodeStream::spawn(&av, &request).unwrap();
    let first = stream.next_frame().unwrap();
    let next = stream.next_frame().unwrap();

    assert_eq!(first, expected);
    assert_eq!((first.width, first.height), (next.width, next.height));
    assert!(first.width <= 120 && first.height <= 68);
    assert_ne!(first.rgba, next.rgba);
}

#[test]
fn decode_frame_scales_within_box() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let req = FrameRequest {
        time_secs: 0.5,
        max_size: (120, 68),
        tolerance_secs: 1.0,
        apply_rotation: true,
    };
    let (_t, frame) = decode_frame_at(&av, &req).unwrap();
    // 320x240 into 120x68 → height-limited (68), width 90.
    assert!(frame.width <= 120 && frame.height <= 68);
    assert_eq!(
        frame.rgba.len(),
        frame.width as usize * frame.height as usize * 4
    );
}

#[test]
fn extract_pcm_yields_16k_mono() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let pcm = extract_pcm(&av, &spec, None).unwrap();
    // ~2 s of 16 kHz mono ≈ 32000 samples (allow generous tolerance).
    assert!(pcm.samples_f32.len() > 24_000 && pcm.samples_f32.len() < 40_000);
    assert!((pcm.duration_secs() - 2.0).abs() < 0.5);
}

#[test]
fn extract_pcm_range_is_shorter() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    // 0.5 s window ≈ 8000 samples.
    let pcm = extract_pcm(&av, &spec, Some((0.5, 1.0))).unwrap();
    let n = pcm.samples_f32.len();
    assert!(n > 4_000 && n < 12_000, "got {n} samples for a 0.5s window");
}

#[test]
fn extract_pcm_no_audio_track_errors() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let video_only = dir.path().join("v.mp4");
    let ok = Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=1:size=64x64:rate=5",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(&video_only)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let err = extract_pcm(&video_only, &spec, None);
    assert!(
        err.is_err(),
        "expected NoTrack error for video without audio"
    );
}

#[test]
fn extract_pcm_empty_stdout_errors_not_silent_buffer() {
    // Regression for the "ffmpeg exits 0 but emits no PCM" case: a range window
    // entirely past the media end seeks past EOF, so ffmpeg succeeds yet writes
    // zero bytes. extract_pcm must surface NoTrack rather than return an empty
    // buffer — an empty buffer downstream poisons the waveform cache with an
    // all-1.0 flat band.
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    // The clip is ~2 s long; ask for [5.0, 6.0) → past EOF → empty stdout.
    let res = extract_pcm(&av, &spec, Some((5.0, 6.0)));
    assert!(
        res.is_err(),
        "expected an error for an empty PCM window, not a silent buffer"
    );
}

#[test]
fn waveform_has_expected_bucket_count() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let audio = dir.path().join("a.wav");
    if !make_audio(&audio) {
        return;
    }
    // 1 s → max(4000, 150) = 4000 buckets, values in [0,1].
    let wf = waveform(&audio, 1.0).unwrap();
    assert_eq!(wf.len(), 4000);
    assert!(wf.iter().all(|&v| (0.0..=1.0).contains(&v)));
    // A 220 Hz tone is loud → at least some buckets well below 1 (not silence).
    let min = wf.iter().copied().fold(f32::INFINITY, f32::min);
    assert!(min < 0.5, "expected loud buckets, min={min}");
}

#[test]
fn waveform_decodes_audio_from_mp4_video_container() {
    // Regression guard: the waveform path must decode the audio track that lives
    // INSIDE a video container (the common case — a clip's `media_ref` points at
    // the video file, and its linked audio reuses that ref). The earlier
    // pure-Rust decoder failed on many such containers while ffmpeg probe/thumb
    // succeeded, so the audio clip rendered as a flat band with no waveform.
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4"); // H.264 video + AAC audio
    if !make_av(&av) {
        return;
    }
    // 2 s → max(4000, 2*150) = 4000 buckets, values in [0,1].
    let wf = waveform(&av, 2.0).unwrap();
    assert_eq!(wf.len(), 4000);
    assert!(wf.iter().all(|&v| (0.0..=1.0).contains(&v)));
    // The 440 Hz sine track is loud → some buckets well below 1 (not silence).
    let min = wf.iter().copied().fold(f32::INFINITY, f32::min);
    assert!(
        min < 0.5,
        "expected loud buckets from the AAC track, min={min}"
    );
}

#[test]
fn video_thumbnails_generates_and_caches() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let cache = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }

    // 2 s clip (<10) → interval 1 → times 0,1 → up to 2 thumbnails.
    let thumbs = video_thumbnails(cache.path(), &av, 2.0, None).unwrap();
    assert!(!thumbs.is_empty());
    assert!(thumbs.len() <= 2);
    // Tiles scaled within the 120x68 box.
    assert!(thumbs[0].image.width <= 120 && thumbs[0].image.height <= 68);

    // Second call hits the sprite cache and returns the same count.
    let again = video_thumbnails(cache.path(), &av, 2.0, None).unwrap();
    assert_eq!(again.len(), thumbs.len());
}

#[test]
fn encode_roundtrip_produces_playable_video() {
    if !ffmpeg_available() || !ffprobe_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("out.mp4");

    let preset = ExportPreset::new(VideoCodec::H264, ExportResolution::P720);
    let (w, h) = (64u32, 64u32);
    let mut enc = VideoEncoder::new(&out, w, h, 10, &preset).unwrap();
    // Push 10 frames of solid color.
    for i in 0..10u8 {
        let mut rgba = vec![0u8; (w * h * 4) as usize];
        for px in rgba.chunks_exact_mut(4) {
            px[0] = i * 20;
            px[1] = 100;
            px[2] = 200;
            px[3] = 255;
        }
        enc.push_frame(&opentake_media::RgbaFrame::new(w, h, rgba))
            .unwrap();
    }
    enc.finish().unwrap();

    // The output decodes back to a 64x64 video of ~1 s.
    let p = probe(&out).unwrap();
    assert!(p.has_video);
    assert_eq!(p.width, Some(64));
    assert_eq!(p.height, Some(64));
    assert!(p.duration_secs > 0.5);

    // Ensure the encode module's preset arg builder agrees with reality.
    let _ = encode::preset::even_dimension(63); // referenced for coverage
}

fn encode_codec_roundtrip(codec: VideoCodec, extension: &str, expected_codec: &str) {
    if !ffmpeg_available() || !ffprobe_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join(format!("roundtrip.{extension}"));
    let preset = ExportPreset::new(codec, ExportResolution::P720);
    let (width, height) = (64_u32, 64_u32);
    let mut encoder = VideoEncoder::new(&out, width, height, 10, &preset).unwrap();
    for index in 0..6_u8 {
        let mut rgba = vec![0_u8; (width * height * 4) as usize];
        for pixel in rgba.chunks_exact_mut(4) {
            pixel.copy_from_slice(&[index.saturating_mul(30), 80, 180, 255]);
        }
        encoder
            .push_frame(&opentake_media::RgbaFrame::new(width, height, rgba))
            .unwrap();
    }
    encoder.finish().unwrap();

    let codec_name = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=codec_name",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(&out)
        .output()
        .unwrap();
    assert!(codec_name.status.success());
    assert_eq!(
        String::from_utf8_lossy(&codec_name.stdout).trim(),
        expected_codec
    );
    let format_name = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "format=format_name",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(&out)
        .output()
        .unwrap();
    assert!(format_name.status.success());
    assert!(
        String::from_utf8_lossy(&format_name.stdout)
            .split(',')
            .any(|name| name.trim() == extension),
        "ffprobe format must include {extension}"
    );
    let media = probe(&out).unwrap();
    assert!(media.has_video);
    assert_eq!(media.width, Some(width));
    assert_eq!(media.height, Some(height));
}

#[test]
fn encode_h265_roundtrip_produces_hevc_mp4() {
    encode_codec_roundtrip(VideoCodec::H265, "mp4", "hevc");
}

#[test]
fn encode_prores_roundtrip_produces_prores_mov() {
    encode_codec_roundtrip(VideoCodec::ProRes422, "mov", "prores");
}

#[test]
fn prores_4444_roundtrip_preserves_alpha_plane() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("SKIP: ffmpeg/ffprobe unavailable");
        return;
    }
    let root = tempfile::tempdir().unwrap();
    let output = root.path().join("alpha.mov");
    let preset = ExportPreset::new(VideoCodec::ProRes4444, ExportResolution::P720);
    let mut encoder = VideoEncoder::new(&output, 2, 2, 1, &preset).unwrap();
    encoder
        .push_frame(&RgbaFrame {
            width: 2,
            height: 2,
            rgba: vec![
                255, 0, 0, 0, 0, 255, 0, 85, 0, 0, 255, 170, 255, 255, 255, 255,
            ],
        })
        .unwrap();
    encoder.finish().unwrap();
    let decoded = decode_frame_at(
        &output,
        &FrameRequest {
            max_size: (2, 2),
            tolerance_secs: 0.0,
            ..FrameRequest::default()
        },
    )
    .unwrap()
    .1;
    let alpha = decoded
        .rgba
        .chunks_exact(4)
        .map(|pixel| pixel[3])
        .collect::<Vec<_>>();
    for (actual, expected) in alpha.iter().zip([0_u8, 85, 170, 255]) {
        assert!(actual.abs_diff(expected) <= 3, "{alpha:?}");
    }
}

#[test]
#[ignore = "requires OPENTAKE_MAIN10_FIXTURE pointing at a real HEVC Main10 clip"]
fn continuous_decode_scales_real_main10_frames_without_corruption() {
    let path = std::env::var_os("OPENTAKE_MAIN10_FIXTURE")
        .map(std::path::PathBuf::from)
        .expect("set OPENTAKE_MAIN10_FIXTURE");
    let mut request = VideoStreamRequest::new(path, 30);
    request.start_frame = 1_572;
    request.end_frame = Some(request.start_frame + 90);
    request.max_size = (1_920, 1_080);

    let stream = spawn_video_stream(request).unwrap();
    for _ in 0..90 {
        let decoded = stream
            .receiver()
            .recv_timeout(std::time::Duration::from_secs(10))
            .expect("continuous decoder frame")
            .expect("continuous decoder success");

        assert_eq!((decoded.frame.width, decoded.frame.height), (1_920, 1_080));
        assert_eq!(decoded.frame.rgba.len(), 1_920 * 1_080 * 4);
        let neon_green = decoded
            .frame
            .rgba
            .chunks_exact(4)
            .filter(|pixel| pixel[0] < 32 && pixel[1] > 224 && pixel[2] < 32)
            .count();
        assert!(
            neon_green < decoded.frame.pixel_count() / 100,
            "frame {} contains {neon_green} neon-green pixels",
            decoded.source_frame
        );
    }
}
